apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: {name}
    spec:
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        env:
          - name: PORT
            value: "5000"
          - name: NODE_ENV
            value: production
          - name: API_BASE_URL
            value: "https://api.apihighways.org"
          - name: SHOW_FEEDBACK
            value: "false"
          - name: SHOW_SEARCH_SUGGESTIONS
            value: "false"
          - name: SHOW_RECENT_DATASETS
            value: "false"
          - name: GOOGLE_ANALYTICS
            value: "UA-90561944-1"
          - name: TWITTER_ACCESS_TOKEN_KEY
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: WEB_TWITTER_ACCESS_TOKEN_KEY
          - name: TWITTER_ACCESS_TOKEN_SECRET
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: WEB_TWITTER_ACCESS_TOKEN_SECRET
          - name: TWITTER_CONSUMER_KEY
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: WEB_TWITTER_CONSUMER_KEY
          - name: TWITTER_CONSUMER_SECRET
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: WEB_TWITTER_CONSUMER_SECRET

        ports:
          - containerPort: 3000

      restartPolicy: Always
