apiVersion: v1
kind: Service
metadata:
 labels:
   name: {name}
 name: {name}
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    name: {name}
